=encoding utf8

=head1 NAME

h2url - HTTP2 CURL 

=head1 SYNOPSIS

 h2url [URL] [OPTION]

=head1 DESCRIPTION

http2 curl utility

=head1 OPTIONS

B<-h>, B<--help>          display this help and exit

B<-v>, B<--version>       display this version and exit

=head1 EXAMPLE

h2url "https://www.google.com"

=head1 COPYRIGHT

Copyright (C) 2017 Verizon.  All Rights Reserved.
Apache License: Version 2.0, January 2004 <http://www.apache.org/licenses/LICENSE-2.0>

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

=head1 SEE ALSO

Source code available at https://github.com/VerizonDigital/hurl
